version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=henrique
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    networks:
    - pg_net
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=henriquemonteiro037@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "5050:80"
    networks:
    - pg_net

networks:
  pg_net: