@url = https://3333-henrique998-emailn2-5wivhr38yuy.ws-us107.gitpod.io
@identity_provider = https://8080-henrique998-emailn2-5wivhr38yuy.ws-us107.gitpod.io

###

POST {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
  "name": "change",
  "content": "campaign change",
  "emails": ["jhondoe2@gmail.com", "henrique3@gmail.com"]
}

###

GET {{url}}/campaigns/cms1qm3giqctpvc88rfg
Authorization: Bearer {{access_token}}

### 

PATCH {{url}}/campaigns/cancel/cmjbr3fpocjjjdtkomrg

### 

DELETE {{url}}/campaigns/delete/cmkpmpnpoceq36mo3vtg

###
# @name token
POST {{identity_provider}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=henriquemonteiro037@gmail.com&password=123456&grant_type=password

###
@access_token = {{token.response.body.access_token}}